# Generated by Django 4.0.4 on 2022-04-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_model', models.TextField()),
                ('date_of_create', models.DateField()),
                ('price', models.IntegerField()),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machins',
            },
        ),
    ]
